# Generated by Django 6.0.4 on 2026-04-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='address',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
